modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheCSDev/mc-tcdcommons/issues" #optional

[[mods]] #mandatory
displayName="TCD Commons API" #mandatory
modId="tcdcommons" #mandatory
version="2.2+1.18.2" #mandatory
authors="TheCSDev" #optional
credits="See authors." #optional
displayURL="https://github.com/TheCSDev/mc-tcdcommons" #optional
logoFile="tcdcommons_icon.png" #optional
description='''My personal API library for my mods. It aims to improve performance by avoiding rewriting the same code, and to speed up the mod development process.'''

[[dependencies.tcdcommons]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.tcdcommons]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
